// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dependencies

import (
	"worker-nicepay/application/services"
	"worker-nicepay/infrastructure/gateway/nicepay"
	"worker-nicepay/infrastructure/publishers"
	"worker-nicepay/infrastructure/service"
)

// Injectors from wire.go:

func WireCreatePaymentService() *services.CreatePaymentService {
	nicepayGateway := ProvideNicepayGateway()
	nicePayTransactionService := ProvideTransactionService()
	createPaymentService := services.NewCreatePaymentService(nicepayGateway, nicePayTransactionService)
	return createPaymentService
}

func WireNicepayGateway() *nicepay.NicepayGateway {
	nicepayGateway := ProvideNicepayGateway()
	return nicepayGateway
}

func WireNicepayTransactionService() *service.NicePayTransactionService {
	nicePayTransactionService := ProvideTransactionService()
	return nicePayTransactionService
}

func WirePublisher() *publishers.PublisherLog {
	publisherLog := ProvidePublisher()
	return publisherLog
}
