// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dependencies

import (
	"payment-airpay/application/services"
	"payment-airpay/infrastructure/gateway/xendit"
	"payment-airpay/infrastructure/publishers"
	"payment-airpay/infrastructure/service"
)

// Injectors from wire.go:

func WireCreatePaymentService() *services.CreatePaymentService {
	xenditGateway := ProvideXenditGateway()
	PaymentXendit := ProvideTransactionService()
	createPaymentService := services.NewCreatePaymentService(xenditGateway, PaymentXendit)
	return createPaymentService
}

func WireXenditGateway() *xendit.XenditGateway {
	xenditGateway := ProvideXenditGateway()
	return xenditGateway
}

func WireTransactionService() *service.PaymentXendit {
	PaymentXendit := ProvideTransactionService()
	return PaymentXendit
}

func WirePublisher() *publishers.PublisherLog {
	publisherLog := ProvidePublisher()
	return publisherLog
}
