package constant

const (
	PAYMENT_STATUS_PENDING = "PENDING"
	PAYMENT_STATUS_SUCCESS = "SUCCESS"
	PAYMENT_STATUS_FAILED  = "FAILED"
	PAYMENT_STATUS_CANCEL  = "CANCEL"
	PAYMENT_STATUS_EXPIRED = "EXPIRED"
)
